version: '3.7'

networks:
  webservice_network:
    driver: bridge

services:

  devroastproject:
    image: devroastproject
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - devroast/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:12.2-alpine
    volumes:
      - ./pgdata/:/var/lib/postgresql/data/devroast
    ports:
      - 543:5432
    env_file:
      - devroast/.env

  redis:
    image: redis:5.0.3-alpine
    networks:
      [webservice_network]
    dns:
      - 8.8.8.8
