version: "3.7"

networks:
  webservice_network:
    driver: bridge

services:
  django:
    image: devroastproject
    networks: [webservice_network]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      # neither: no folders appear, but the static doesn't get collected
      # both: mediafiles and staticfiles appear empty, resets work
      - .:/usr/src/app/ # without, staticfiles appears full, mediafiles does not appear, resets work
      - static:/usr/src/app/staticfiles
      - media:/usr/src/app/mediafiles
      - .:/app/code # without, mediafiles and staticfiles appear empty, resets do not work, static is not collected correctly
    env_file:
      - devroast/.env
    depends_on:
      - postgres
    restart: always
    command: sh ./startup_scripts.sh

  react:
    networks: [webservice_network]
    build:
      context: .
      dockerfile: Dockerfile.react
    stdin_open: true
    ports:
      - 3000:3000
    env_file:
      - devroast/.env
    depends_on:
      - postgres
      - django
    volumes:
      - type: bind
        source: ./frontend/react-frontend
        target: /app
      - "/app/node_modules"

  postgres:
    image: postgres:12.2-alpine
    networks: [webservice_network]
    volumes:
      - devroast:/var/lib/postgresql/data/
    ports:
      - 543:5432
    env_file:
      - devroast/.env

  redis:
    image: redis:5.0.3-alpine
    networks: [webservice_network]
    dns:
      - 8.8.8.8

volumes:
  devroast:
  static:
  media:
