blank_issues_enabled: false
contact_links:
  - name: ❓ DevRoastProject Slack Channel
    url: https://pugetsoundpython.slack.com/app_redirect?channel=devroastproject
    about: Please ask and answer questions here. 🏥
